[package]
name = "pan-lang-rs"
version = "0.1.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
failure_derive = "0.1.3"
futures-preview = "0.3.0-alpha.13"
gc = "0.3.2"
gc_derive = "0.3.2"
lazy_static = "1.2.0"
ordered-float = "1.0.1"
